# Generated by Django 5.1.6 on 2025-03-07 02:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelCore", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="industry",
            options={"verbose_name": "產業", "verbose_name_plural": "產業"},
        ),
        migrations.AlterModelOptions(
            name="keyword",
            options={"verbose_name": "關鍵字", "verbose_name_plural": "關鍵字"},
        ),
        migrations.AlterModelOptions(
            name="newsarticle",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "新聞文章",
                "verbose_name_plural": "新聞文章",
            },
        ),
        migrations.RemoveField(
            model_name="industry",
            name="description",
        ),
        migrations.AddField(
            model_name="industry",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="建立時間"
            ),
        ),
        migrations.AddField(
            model_name="industry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AddField(
            model_name="keyword",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="建立時間"
            ),
        ),
        migrations.AddField(
            model_name="keyword",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="建立時間"
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="industries",
            field=models.ManyToManyField(
                blank=True,
                related_name="news_articles",
                to="modelCore.industry",
                verbose_name="相關產業",
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                related_name="news_articles",
                to="modelCore.keyword",
                verbose_name="相關關鍵字",
            ),
        ),
        migrations.AlterField(
            model_name="industry",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="產業名稱"),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="keywords",
                to="modelCore.industry",
                verbose_name="相關產業",
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="keyword",
            field=models.CharField(max_length=50, verbose_name="關鍵字"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="published_at",
            field=models.DateTimeField(null=True, verbose_name="發布時間"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="source",
            field=models.CharField(max_length=100, verbose_name="來源"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="title",
            field=models.CharField(max_length=200, verbose_name="標題"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="url",
            field=models.URLField(unique=True, verbose_name="連結"),
        ),
    ]
