# Generated by Django 5.1.6 on 2025-03-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelCore", "0002_alter_industry_options_alter_keyword_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="keyword",
            field=models.CharField(max_length=50, unique=True, verbose_name="關鍵字"),
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(
                fields=["keyword"], name="modelCore_k_keyword_9370fd_idx"
            ),
        ),
    ]
